### ISSUE TITLE
How should I choose value of min_sim?

### ISSUE THREAD

**Issue by suay1113** [xiaoxiong74/face-cluster-by-infomap#2]
我测试了一下您的代码，感觉效果不错，而且代码清晰

有一个问题，min_sim的值应该如何调整？可以提供一些对于不同数据集的参考吗？

**Comment by xiaoxiong74** [comment]
> 我测试了一下您的代码，感觉效果不错，而且代码清晰
> 
> 有一个问题，min_sim的值应该如何调整？可以提供一些对于不同数据集的参考吗？

这里的min_sim可以理解为两个点属于同一类的相似度阈值。这个值比较依赖抽取的特征及图片质量。就比如人脸特征，如果你的人脸特征抽取的模型很好，可能0.5就能区分不同人脸，但假设大多数人脸都戴了口罩，可能区分能力就没那么强，可能就要设置为0.6或更高了。这个值在实际应用中，可以通过标注一些场景数据来调整这个值得到最优的指标来确定。
